# Generated by Django 5.2.5 on 2025-08-17 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('role_code', models.CharField(choices=[('MASTER_ADMIN', 'Administrador Master'), ('SECTOR_ADMIN', 'Administrador de Setor'), ('SECTOR_OPERATOR', 'Operador de Setor'), ('EMPLOYEE', 'Funcionário')], max_length=20, verbose_name='Papel')),
                ('sector_code', models.CharField(blank=True, choices=[('RH', 'Recursos Humanos'), ('TRIBUTOS', 'Tributos'), ('LICITACAO', 'Licitação'), ('OBRAS', 'Obras')], max_length=20, null=True, verbose_name='Setor')),
                ('security_code', models.CharField(max_length=8, verbose_name='Código de Segurança')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Token de Convite')),
                ('expires_at', models.DateTimeField(verbose_name='Expira em')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Aceito em')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('EXPIRED', 'Expirado'), ('ACCEPTED', 'Aceito'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites_sent', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Convite de Usuário',
                'verbose_name_plural': 'Convites de Usuários',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='users_useri_email_63c5b6_idx'), models.Index(fields=['token'], name='users_useri_token_514322_idx'), models.Index(fields=['security_code'], name='users_useri_securit_6d7a1c_idx'), models.Index(fields=['status', 'expires_at'], name='users_useri_status_08f246_idx')],
            },
        ),
    ]
