# Generated by Django 5.2.5 on 2025-08-16 19:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Número do Contrato')),
                ('supplier_name', models.CharField(max_length=200, verbose_name='Nome do Fornecedor')),
                ('supplier_doc', models.CharField(max_length=18, verbose_name='CPF/CNPJ do Fornecedor')),
                ('start_dt', models.DateField(verbose_name='Data de Início')),
                ('end_dt', models.DateField(verbose_name='Data de Fim')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Total')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ATIVO', 'Ativo'), ('SUSPENSO', 'Suspenso'), ('ENCERRADO', 'Encerrado'), ('RESCINDIDO', 'Rescindido')], default='RASCUNHO', max_length=20, verbose_name='Status')),
                ('objeto', models.TextField(verbose_name='Objeto do Contrato')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade', models.CharField(choices=[('CONCORRENCIA', 'Concorrência'), ('PREGAO', 'Pregão'), ('CONCURSO', 'Concurso'), ('LEILAO', 'Leilão'), ('TOMADA_PRECOS', 'Tomada de Preços'), ('CONVITE', 'Convite'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Modalidade')),
                ('objeto', models.TextField(verbose_name='Objeto da Licitação')),
                ('numero_processo', models.CharField(max_length=50, unique=True, verbose_name='Número do Processo')),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Estimado')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ABERTA', 'Aberta'), ('EM_ANDAMENTO', 'Em Andamento'), ('SUSPENSA', 'Suspensa'), ('ENCERRADA', 'Encerrada'), ('ANULADA', 'Anulada'), ('HOMOLOGADA', 'Homologada')], default='RASCUNHO', max_length=20, verbose_name='Status')),
                ('data_abertura', models.DateField(verbose_name='Data de Abertura')),
                ('data_encerramento', models.DateField(verbose_name='Data de Encerramento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Processo de Licitação',
                'verbose_name_plural': 'Processos de Licitação',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=200, verbose_name='Descrição')),
                ('due_dt', models.DateField(verbose_name='Data de Vencimento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor do Marco')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('ATRASADO', 'Atrasado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='licitacao.contract', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Marco do Contrato',
                'verbose_name_plural': 'Marcos do Contrato',
                'ordering': ['contract', 'due_dt'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='procurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='licitacao.procurement', verbose_name='Processo de Licitação'),
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=200, verbose_name='Nome do Fornecedor')),
                ('supplier_doc', models.CharField(max_length=18, verbose_name='CPF/CNPJ do Fornecedor')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor da Proposta')),
                ('classificacao', models.PositiveIntegerField(blank=True, null=True, verbose_name='Classificação')),
                ('status', models.CharField(choices=[('RECEBIDA', 'Recebida'), ('HABILITADA', 'Habilitada'), ('DESABILITADA', 'Desabilitada'), ('CLASSIFICADA', 'Classificada'), ('DESCLASSIFICADA', 'Desclassificada')], default='RECEBIDA', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='licitacao.procurement', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'Proposta',
                'verbose_name_plural': 'Propostas',
                'ordering': ['procurement', 'classificacao', 'valor'],
                'unique_together': {('procurement', 'supplier_doc')},
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_adjudicado', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Adjudicado')),
                ('homolog_dt', models.DateTimeField(verbose_name='Data da Homologação')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('procurement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='award', to='licitacao.procurement', verbose_name='Processo')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='licitacao.proposal', verbose_name='Fornecedor Vencedor')),
            ],
            options={
                'verbose_name': 'Adjudicação',
                'verbose_name_plural': 'Adjudicações',
                'ordering': ['-homolog_dt'],
            },
        ),
        migrations.CreateModel(
            name='ProcPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('PUBLICACAO', 'Publicação'), ('INSCRICAO', 'Inscrição'), ('HABILITACAO', 'Habilitação'), ('PROPOSTAS', 'Propostas'), ('ABERTURA', 'Abertura'), ('JULGAMENTO', 'Julgamento'), ('HOMOLOGACAO', 'Homologação'), ('ADJUDICACAO', 'Adjudicação')], max_length=20, verbose_name='Fase')),
                ('start_dt', models.DateTimeField(verbose_name='Data de Início')),
                ('end_dt', models.DateTimeField(verbose_name='Data de Fim')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='licitacao.procurement', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'Fase do Processo',
                'verbose_name_plural': 'Fases do Processo',
                'ordering': ['procurement', 'start_dt'],
                'unique_together': {('procurement', 'fase')},
            },
        ),
    ]
