# Generated by Django 5.2.5 on 2025-08-16 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matrícula')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('lotacao', models.CharField(max_length=100, verbose_name='Lotação')),
                ('regime', models.CharField(choices=[('CLT', 'CLT'), ('ESTATUTARIO', 'Estatutário'), ('TEMPORARIO', 'Temporário'), ('TERCEIRIZADO', 'Terceirizado')], default='CLT', max_length=20, verbose_name='Regime')),
                ('admissao_dt', models.DateField(verbose_name='Data de Admissão')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('APOSENTADO', 'Aposentado'), ('DEMITIDO', 'Demitido')], default='ATIVO', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(verbose_name='Competência')),
                ('bruto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Bruto')),
                ('descontos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descontos')),
                ('liquido', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Líquido')),
                ('pdf_url', models.URLField(blank=True, null=True, verbose_name='URL do PDF')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='payslips/', verbose_name='Arquivo PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Contracheque',
                'verbose_name_plural': 'Contracheques',
                'ordering': ['-competencia', 'employee__user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='VacationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Início do Período')),
                ('period_end', models.DateField(verbose_name='Fim do Período')),
                ('days_requested', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Dias Solicitados')),
                ('reason', models.TextField(blank=True, verbose_name='Justificativa')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Aprovado em')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motivo da Rejeição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Solicitação de Férias',
                'verbose_name_plural': 'Solicitações de Férias',
                'ordering': ['-created_at'],
            },
        ),
    ]
