# Generated by Django 5.2.5 on 2025-08-16 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Criar'), ('READ', 'Ler'), ('UPDATE', 'Atualizar'), ('DELETE', 'Deletar'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('APPROVE', 'Aprovar'), ('REJECT', 'Rejeitar'), ('UPLOAD', 'Upload'), ('DOWNLOAD', 'Download')], max_length=20, verbose_name='Ação')),
                ('entity', models.CharField(max_length=100, verbose_name='Entidade')),
                ('entity_id', models.PositiveIntegerField(verbose_name='ID da Entidade')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID do Objeto')),
                ('payload_json', models.JSONField(blank=True, null=True, verbose_name='Payload JSON')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('method', models.CharField(blank=True, max_length=10, verbose_name='Método HTTP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Conteúdo')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-created_at'],
            },
        ),
    ]
