# Generated by Django 5.2.5 on 2025-08-16 19:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licitacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome da Obra')),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('address', models.TextField(verbose_name='Endereço')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Orçamento')),
                ('status', models.CharField(choices=[('PLANEJAMENTO', 'Planejamento'), ('LICITACAO', 'Licitação'), ('EXECUCAO', 'Em Execução'), ('PARALISADA', 'Paralisada'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PLANEJAMENTO', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('expected_end_date', models.DateField(verbose_name='Data Prevista de Conclusão')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='Data Real de Conclusão')),
                ('description', models.TextField(verbose_name='Descrição da Obra')),
                ('responsible', models.CharField(max_length=200, verbose_name='Responsável')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_projects', to='licitacao.contract', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Obra/Projeto',
                'verbose_name_plural': 'Obras/Projetos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('photo', models.ImageField(upload_to='work_photos/', verbose_name='Foto')),
                ('taken_date', models.DateField(verbose_name='Data da Foto')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Localização')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='obras.workproject', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Foto da Obra',
                'verbose_name_plural': 'Fotos da Obra',
                'ordering': ['project', '-taken_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_month', models.DateField(verbose_name='Mês de Referência')),
                ('physical_pct', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Progresso Físico (%)')),
                ('financial_pct', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Progresso Financeiro (%)')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_set', to='obras.workproject', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Progresso da Obra',
                'verbose_name_plural': 'Progressos da Obra',
                'ordering': ['project', '-ref_month'],
                'unique_together': {('project', 'ref_month')},
            },
        ),
    ]
