# Generated by Django 5.2.5 on 2025-08-16 19:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_kind', models.CharField(choices=[('ISS', 'ISS'), ('IPTU', 'IPTU'), ('ITBI', 'ITBI'), ('OUTROS', 'Outros')], max_length=10, verbose_name='Tipo de Imposto')),
                ('competence', models.DateField(verbose_name='Competência')),
                ('principal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Principal')),
                ('multa', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Multa')),
                ('juros', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Juros')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EMITIDA', 'Emitida'), ('PAGA', 'Paga'), ('VENCIDA', 'Vencida')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Avaliação/Guia',
                'verbose_name_plural': 'Avaliações/Guias',
                'ordering': ['-competence', 'taxpayer__name'],
            },
        ),
        migrations.CreateModel(
            name='Taxpayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome/Razão Social')),
                ('doc', models.CharField(max_length=18, unique=True, verbose_name='CPF/CNPJ')),
                ('type', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2, verbose_name='Tipo')),
                ('address', models.TextField(verbose_name='Endereço')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Contribuinte',
                'verbose_name_plural': 'Contribuintes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_dt', models.DateField(verbose_name='Data de Vencimento')),
                ('barcode', models.CharField(max_length=100, unique=True, verbose_name='Código de Barras')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor a Pagar')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('payment_dt', models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Pago')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='tributos.assessment', verbose_name='Avaliação')),
            ],
            options={
                'verbose_name': 'Cobrança',
                'verbose_name_plural': 'Cobranças',
                'ordering': ['due_dt', 'assessment__taxpayer__name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Número da NF')),
                ('issue_dt', models.DateField(verbose_name='Data de Emissão')),
                ('service_code', models.CharField(max_length=10, verbose_name='Código do Serviço')),
                ('description', models.TextField(verbose_name='Descrição do Serviço')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('status', models.CharField(choices=[('EMITIDA', 'Emitida'), ('CANCELADA', 'Cancelada'), ('PAGA', 'Paga')], default='EMITIDA', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('taxpayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tributos.taxpayer', verbose_name='Contribuinte')),
            ],
            options={
                'verbose_name': 'Nota Fiscal',
                'verbose_name_plural': 'Notas Fiscais',
                'ordering': ['-issue_dt', 'number'],
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='taxpayer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='tributos.taxpayer', verbose_name='Contribuinte'),
        ),
    ]
